name: Test, Coverage and Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- NEW: Explicitly install dependencies for all parts of the project ---
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install All Dependencies
        run: |
          npm install
          npm install --prefix backend
          npm install --prefix frontend

      # --- UPDATED: Cypress action now assumes a ready environment ---
      - name: Run Cypress Tests and Collect Coverage
        uses: cypress-io/github-action@v6
        with:
          # This command will now work because npm-run-all is installed
          start: npm run start:coverage
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          # We can safely disable the action's install step as we did it manually
          install: false

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: ./coverage