name: Test, Coverage and Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install All Dependencies
        run: |
          echo "--- Installing root dependencies in $(pwd) ---"
          npm install
          
          echo "--- Installing backend dependencies ---"
          (cd backend && npm install)
          
          echo "--- Installing frontend dependencies ---"
          (cd frontend && npm install)

      - name: Run Cypress Tests and Collect Coverage
        uses: cypress-io/github-action@v6
        with:
          start: npm run start:coverage
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          install: false

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: ./coverage