name: Test, Coverage and Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install All Dependencies
        run: |
          npm install
          (cd backend && npm install)
          (cd frontend && npm install)

      # This step now fixes the permissions for npm-run-all, cypress,
      # start-server-and-test, and any other package executable.
      - name: Add execute permissions to all scripts
        run: chmod +x ./node_modules/.bin/*

      - name: Run E2E Tests
        run: npm run test:ci

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: ./coverage